-- MySQL Script generated by MySQL Workbench
-- Sat Sep  8 15:46:10 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library` DEFAULT CHARACTER SET utf8 ;
USE `library` ;

-- -----------------------------------------------------
-- Table `library`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`book` (
  `book_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `book_Title` VARCHAR(255) NOT NULL,
  `book_Description` VARCHAR(255) NOT NULL,
  `book_Author` VARCHAR(255) NOT NULL,
  `book_Category` VARCHAR(255) NOT NULL,
  `book_Quantity` INT(11) NOT NULL,
  PRIMARY KEY (`book_ID`),
  UNIQUE INDEX `book_ISBN_UNIQUE` (`book_ID` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `library`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`user` (
  `user_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `user_Name` VARCHAR(255) NOT NULL,
  `user_Email` VARCHAR(255) NOT NULL,
  `user_Password` VARCHAR(255) NOT NULL,
  `user_Role` TINYINT(3) NOT NULL,
  PRIMARY KEY (`user_ID`),
  UNIQUE INDEX `user_ID_UNIQUE` (`user_ID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `library`.`borrow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`borrow` (
  `borrow_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `book_ID` INT(11) NOT NULL,
  `user_ID` INT(11) NOT NULL,
  `borrow_Date` DATETIME NOT NULL,
  `return_Date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`borrow_ID`),
  UNIQUE INDEX `borrow_ID_UNIQUE` (`borrow_ID` ASC),
  INDEX `user_ID_idx` (`user_ID` ASC),
  INDEX `book_ID_idx` (`book_ID` ASC),
  CONSTRAINT `user_ID`
    FOREIGN KEY (`user_ID`)
    REFERENCES `library`.`user` (`user_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `book_ID`
    FOREIGN KEY (`book_ID`)
    REFERENCES `library`.`book` (`book_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
